[project]
name = "SalesmanBot"
version = "0.0.1"
description = "A chatbot that trains door-to-door salespeople to be more effective."
authors = [{ name = "Andreas Loutzidis", email = "aloutzidis@gmail.com" }]
dependencies = [
    "aiohttp==3.9.0",
    "aiosignal==1.3.1",
    "annotated-types==0.6.0",
    "anyio==3.7.1",
    "async-timeout==4.0.3",
    "attrs==23.1.0",
    "certifi==2023.11.17",
    "charset-normalizer==3.3.2",
    "dataclasses-json==0.6.2",
    "distro==1.8.0",
    "exceptiongroup==1.1.3",
    "frozenlist==1.4.0",
    "h11==0.14.0",
    "httpcore==1.0.2",
    "httpx==0.25.1",
    "idna==3.4",
    "jsonpatch==1.33",
    "jsonpointer==2.4",
    "langchain==0.0.338",
    "langsmith==0.0.65",
    "marshmallow==3.20.1",
    "multidict==6.0.4",
    "mypy-extensions==1.0.0",
    "numpy==1.26.2",
    "openai==1.3.3",
    "packaging==23.2",
    "pydantic==2.5.1",
    "pydantic-core==2.14.3",
    "PyYAML==6.0.1",
    "requests==2.31.0",
    "sniffio==1.3.0",
    "SQLAlchemy==2.0.23",
    "tenacity==8.2.3",
    "tqdm==4.66.1",
    "typing-inspect==0.9.0",
    "typing-extensions==4.8.0",
    "urllib3==2.1.0",
    "yarl==1.9.2",
]
requires-python = ">=3.9"
readme = "README.md"
license = { text = "MIT" }
